# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 386)
        MainWindow.setStyleSheet("background-color: rgb(59, 59, 59)")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #000000;\n"
"    font-size: 10pt;\n"
"    font-family: \"Segoe Print\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #000000;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"} ")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 41))
        self.label.setStyleSheet("font-family: \"Segoe Print\"; \n"
"color: white")
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.GeneratePush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GeneratePush.setGeometry(QtCore.QRect(150, 70, 101, 23))
        self.GeneratePush.setStyleSheet("")
        self.GeneratePush.setObjectName("GeneratePush")
        self.ClearPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearPush.setGeometry(QtCore.QRect(74, 70, 71, 23))
        self.ClearPush.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #000000;\n"
"    font-size: 10pt;\n"
"    font-family: \"Segoe Print\";\n"
"    color: rgb(255,255,255);\n"
"    \n"
"}  \n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255)\n"
"} ")
        self.ClearPush.setObjectName("ClearPush")
        self.RandomPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RandomPush.setGeometry(QtCore.QRect(260, 70, 101, 23))
        self.RandomPush.setStyleSheet("")
        self.RandomPush.setObjectName("RandomPush")
        self.formGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.formGroupBox.setGeometry(QtCore.QRect(450, 5, 160, 221))
        self.formGroupBox.setStyleSheet("QCheckBox {\n"
"    font-family: \"Segoe Print\"; \n"
"    color: white;\n"
"}\n"
"    \n"
"QCheckBox:hover {\n"
"    border-radius: 10px;\n"
"    border: 2px solid white;\n"
"    \n"
"\n"
"}")
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 4, 10, -1)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.formGroupBox)
        self.label_2.setStyleSheet("font-family: \"Segoe Print\"; \n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.NumBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.NumBox.setStyleSheet("")
        self.NumBox.setObjectName("NumBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.NumBox)
        self.LetterBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.LetterBox.setStyleSheet("")
        self.LetterBox.setObjectName("LetterBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.LetterBox)
        self.SpecialBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.SpecialBox.setStyleSheet("")
        self.SpecialBox.setObjectName("SpecialBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SpecialBox)
        self.RandBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.RandBox.setStyleSheet("")
        self.RandBox.setObjectName("RandBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.RandBox)
        self.CapsBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.CapsBox.setStyleSheet("")
        self.CapsBox.setObjectName("CapsBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.CapsBox)
        self.BaseBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.BaseBox.setStyleSheet("")
        self.BaseBox.setObjectName("BaseBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.BaseBox)
        self.CopyPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CopyPush.setGeometry(QtCore.QRect(370, 70, 61, 23))
        self.CopyPush.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: #000000;\n"
"    font-size: 10pt;\n"
"    font-family: \"Segoe Print\";\n"
"    color: rgb(255,255,255);\n"
"\n"
"}\n"
"  \n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255)\n"
"} ")
        self.CopyPush.setObjectName("CopyPush")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 360, 71, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 230, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 627, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFileSaver = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFileSaver.setObjectName("menuFileSaver")
        self.menuGenerate_multiply_times = QtWidgets.QMenu(parent=self.menuFileSaver)
        self.menuGenerate_multiply_times.setObjectName("menuGenerate_multiply_times")
        self.menuHashes = QtWidgets.QMenu(parent=self.menuBar)
        self.menuHashes.setObjectName("menuHashes")
        self.menuAbout = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtGui.QAction(parent=MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionMD5 = QtGui.QAction(parent=MainWindow)
        self.actionMD5.setObjectName("actionMD5")
        self.actionsha512 = QtGui.QAction(parent=MainWindow)
        self.actionsha512.setObjectName("actionsha512")
        self.actionsha256 = QtGui.QAction(parent=MainWindow)
        self.actionsha256.setObjectName("actionsha256")
        self.actionsha_1 = QtGui.QAction(parent=MainWindow)
        self.actionsha_1.setObjectName("actionsha_1")
        self.actionblake2b = QtGui.QAction(parent=MainWindow)
        self.actionblake2b.setObjectName("actionblake2b")
        self.actionGenerate_5_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_5_times.setObjectName("actionGenerate_5_times")
        self.actionGenerate_10_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_10_times.setObjectName("actionGenerate_10_times")
        self.actionGenerate_50_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_50_times.setObjectName("actionGenerate_50_times")
        self.actionGenerate_100_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_100_times.setObjectName("actionGenerate_100_times")
        self.action2 = QtGui.QAction(parent=MainWindow)
        self.action2.setObjectName("action2")
        self.action5 = QtGui.QAction(parent=MainWindow)
        self.action5.setObjectName("action5")
        self.action10 = QtGui.QAction(parent=MainWindow)
        self.action10.setObjectName("action10")
        self.action20 = QtGui.QAction(parent=MainWindow)
        self.action20.setObjectName("action20")
        self.action50 = QtGui.QAction(parent=MainWindow)
        self.action50.setObjectName("action50")
        self.action100 = QtGui.QAction(parent=MainWindow)
        self.action100.setObjectName("action100")
        self.actionNot_save = QtGui.QAction(parent=MainWindow)
        self.actionNot_save.setObjectName("actionNot_save")
        self.menuGenerate_multiply_times.addAction(self.action2)
        self.menuGenerate_multiply_times.addAction(self.action5)
        self.menuGenerate_multiply_times.addAction(self.action10)
        self.menuGenerate_multiply_times.addAction(self.action20)
        self.menuGenerate_multiply_times.addAction(self.action50)
        self.menuGenerate_multiply_times.addAction(self.action100)
        self.menuFileSaver.addSeparator()
        self.menuFileSaver.addAction(self.actionFile)
        self.menuFileSaver.addSeparator()
        self.menuFileSaver.addAction(self.menuGenerate_multiply_times.menuAction())
        self.menuHashes.addAction(self.actionMD5)
        self.menuHashes.addAction(self.actionsha512)
        self.menuHashes.addAction(self.actionsha256)
        self.menuHashes.addAction(self.actionsha_1)
        self.menuBar.addAction(self.menuFileSaver.menuAction())
        self.menuBar.addAction(self.menuHashes.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PasswordGenerator"))
        self.label.setText(_translate("MainWindow", "Password:"))
        self.GeneratePush.setText(_translate("MainWindow", "Generate"))
        self.ClearPush.setText(_translate("MainWindow", "Clear"))
        self.RandomPush.setText(_translate("MainWindow", "Random it"))
        self.label_2.setText(_translate("MainWindow", "Config"))
        self.NumBox.setText(_translate("MainWindow", "Numbers"))
        self.LetterBox.setText(_translate("MainWindow", "Letters"))
        self.SpecialBox.setText(_translate("MainWindow", "Special Symbols"))
        self.RandBox.setText(_translate("MainWindow", "Random length"))
        self.CapsBox.setText(_translate("MainWindow", "CAPS"))
        self.BaseBox.setText(_translate("MainWindow", "Base64"))
        self.CopyPush.setText(_translate("MainWindow", "Copy"))
        self.menuFileSaver.setTitle(_translate("MainWindow", "File"))
        self.menuGenerate_multiply_times.setTitle(_translate("MainWindow", "Generate multiply times"))
        self.menuHashes.setTitle(_translate("MainWindow", "Hashes"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionFile.setText(_translate("MainWindow", "Save to file"))
        self.actionMD5.setText(_translate("MainWindow", "md5"))
        self.actionsha512.setText(_translate("MainWindow", "sha512"))
        self.actionsha256.setText(_translate("MainWindow", "sha256"))
        self.actionsha_1.setText(_translate("MainWindow", "sha-1"))
        self.actionblake2b.setText(_translate("MainWindow", "blake2b"))
        self.actionGenerate_5_times.setText(_translate("MainWindow", "Generate 5 times"))
        self.actionGenerate_10_times.setText(_translate("MainWindow", "Generate 10 times"))
        self.actionGenerate_50_times.setText(_translate("MainWindow", "Generate 50 times"))
        self.actionGenerate_100_times.setText(_translate("MainWindow", "Generate 100 times"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action10.setText(_translate("MainWindow", "10"))
        self.action20.setText(_translate("MainWindow", "20"))
        self.action50.setText(_translate("MainWindow", "50"))
        self.action100.setText(_translate("MainWindow", "100"))
        self.actionNot_save.setText(_translate("MainWindow", "Not save"))
