# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# flake8: noqa

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 380)
        MainWindow.setStyleSheet("background-color: rgb(36, 35, 35);\n"
"color: white;")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QLabel {    \n"
"    font: 400 8pt \"Microsoft YaHei UI\";\n"
"    border-color: rgb(36, 35, 35)\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 400 8pt \"Microsoft YaHei UI\";    \n"
"    border-radius: 10px;\n"
"    background-color: #000000;\n"
"    font-size: 10pt;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #000000;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 2px solid rgb(85, 0, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setToolTip("")
        self.lineEdit.setStatusTip("")
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border:  1px solid #ffffff;\n"
"    border-radius: 4px;        \n"
"}")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(5, 20, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.GeneratePush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GeneratePush.setGeometry(QtCore.QRect(150, 70, 101, 23))
        self.GeneratePush.setStyleSheet("")
        self.GeneratePush.setObjectName("GeneratePush")
        self.ClearPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearPush.setGeometry(QtCore.QRect(74, 70, 71, 23))
        self.ClearPush.setStyleSheet("")
        self.ClearPush.setObjectName("ClearPush")
        self.RandomPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RandomPush.setGeometry(QtCore.QRect(255, 70, 91, 23))
        self.RandomPush.setStyleSheet("")
        self.RandomPush.setObjectName("RandomPush")
        self.formGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.formGroupBox.setGeometry(QtCore.QRect(450, 0, 171, 261))
        self.formGroupBox.setStyleSheet("QCheckBox {\n"
"    font: 400 4pt \"Microsoft YaHei UI\";; \n"
"    color: white;\n"
"    font-size: 13px;\n"
"} \n"
"\n"
"QCheckBox:hover {    \n"
"    background-color: rgb(36, 35, 35);\n"
"    color: white;    \n"
"    border-radius: 4px;\n"
"    border: 1px solid #ffffff\n"
"}\n"
"\n"
"QCheckBox:pressed {\n"
"    color: white;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QGroupBox{    \n"
"    border-radius: 10px; \n"
"    border: 1px solid;\n"
"    border-color: #ffffff;\n"
"}\n"
"\n"
"")
        self.formGroupBox.setObjectName("formGroupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.formGroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.NumBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.NumBox.setGeometry(QtCore.QRect(10, 35, 80, 23))
        self.NumBox.setStyleSheet("")
        self.NumBox.setObjectName("NumBox")
        self.LetterBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.LetterBox.setGeometry(QtCore.QRect(10, 64, 65, 23))
        self.LetterBox.setStyleSheet("")
        self.LetterBox.setObjectName("LetterBox")
        self.SpecialBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.SpecialBox.setGeometry(QtCore.QRect(10, 93, 151, 23))
        self.SpecialBox.setStyleSheet("")
        self.SpecialBox.setObjectName("SpecialBox")
        self.RandBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.RandBox.setGeometry(QtCore.QRect(10, 122, 151, 23))
        self.RandBox.setStyleSheet("")
        self.RandBox.setObjectName("RandBox")
        self.CapsBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.CapsBox.setGeometry(QtCore.QRect(10, 151, 57, 23))
        self.CapsBox.setStyleSheet("")
        self.CapsBox.setObjectName("CapsBox")
        self.BaseBox = QtWidgets.QCheckBox(parent=self.formGroupBox)
        self.BaseBox.setGeometry(QtCore.QRect(10, 180, 101, 23))
        self.BaseBox.setStyleSheet("")
        self.BaseBox.setObjectName("BaseBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.formGroupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 231, 31, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setToolTip("")
        self.lineEdit_2.setStatusTip("")
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border:  1px solid #ffffff;\n"
"    border-radius: 4px;        \n"
"}\n"
"\n"
"")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("8")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(parent=self.formGroupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 207, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2.raise_()
        self.NumBox.raise_()
        self.LetterBox.raise_()
        self.SpecialBox.raise_()
        self.RandBox.raise_()
        self.CapsBox.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.BaseBox.raise_()
        self.CopyPush = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CopyPush.setGeometry(QtCore.QRect(348, 70, 100, 23))
        self.CopyPush.setStyleSheet("")
        self.CopyPush.setObjectName("CopyPush")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(475, 335, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 267, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit.raise_()
        self.label.raise_()
        self.GeneratePush.raise_()
        self.ClearPush.raise_()
        self.RandomPush.raise_()
        self.CopyPush.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.formGroupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 623, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFileSaver = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFileSaver.setObjectName("menuFileSaver")
        self.menuHashes = QtWidgets.QMenu(parent=self.menuBar)
        self.menuHashes.setToolTip("")
        self.menuHashes.setStatusTip("")
        self.menuHashes.setAccessibleName("")
        self.menuHashes.setObjectName("menuHashes")
        self.menuAbout = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuChange_language = QtWidgets.QMenu(parent=self.menuAbout)
        self.menuChange_language.setObjectName("menuChange_language")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtGui.QAction(parent=MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionsha512 = QtGui.QAction(parent=MainWindow)
        self.actionsha512.setObjectName("actionsha512")
        self.actionsha256 = QtGui.QAction(parent=MainWindow)
        self.actionsha256.setObjectName("actionsha256")
        self.actionsha_1 = QtGui.QAction(parent=MainWindow)
        self.actionsha_1.setObjectName("actionsha_1")
        self.actionblake2b = QtGui.QAction(parent=MainWindow)
        self.actionblake2b.setObjectName("actionblake2b")
        self.actionGenerate_5_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_5_times.setObjectName("actionGenerate_5_times")
        self.actionGenerate_10_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_10_times.setObjectName("actionGenerate_10_times")
        self.actionGenerate_50_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_50_times.setObjectName("actionGenerate_50_times")
        self.actionGenerate_100_times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_100_times.setObjectName("actionGenerate_100_times")
        self.action2 = QtGui.QAction(parent=MainWindow)
        self.action2.setObjectName("action2")
        self.action5 = QtGui.QAction(parent=MainWindow)
        self.action5.setObjectName("action5")
        self.action10 = QtGui.QAction(parent=MainWindow)
        self.action10.setObjectName("action10")
        self.action20 = QtGui.QAction(parent=MainWindow)
        self.action20.setObjectName("action20")
        self.action50 = QtGui.QAction(parent=MainWindow)
        self.action50.setObjectName("action50")
        self.action100 = QtGui.QAction(parent=MainWindow)
        self.action100.setObjectName("action100")
        self.actionNot_save = QtGui.QAction(parent=MainWindow)
        self.actionNot_save.setObjectName("actionNot_save")
        self.actionGenerate_Multiply_Times = QtGui.QAction(parent=MainWindow)
        self.actionGenerate_Multiply_Times.setObjectName("actionGenerate_Multiply_Times")
        self.actionRussian = QtGui.QAction(parent=MainWindow)
        self.actionRussian.setObjectName("actionRussian")
        self.actionEnglish = QtGui.QAction(parent=MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionMD5 = QtGui.QAction(parent=MainWindow)
        self.actionMD5.setText("md5")
        self.actionMD5.setObjectName("actionMD5")
        self.menuFileSaver.addAction(self.actionGenerate_Multiply_Times)
        self.menuHashes.addAction(self.actionMD5)
        self.menuHashes.addAction(self.actionsha512)
        self.menuHashes.addAction(self.actionsha256)
        self.menuHashes.addAction(self.actionsha_1)
        self.menuChange_language.addSeparator()
        self.menuChange_language.addAction(self.actionRussian)
        self.menuChange_language.addAction(self.actionEnglish)
        self.menuAbout.addAction(self.menuChange_language.menuAction())
        self.menuBar.addAction(self.menuFileSaver.menuAction())
        self.menuBar.addAction(self.menuHashes.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PasswordGenerator"))
        self.label.setText(_translate("MainWindow", "Password:"))
        self.GeneratePush.setText(_translate("MainWindow", "Generate"))
        self.ClearPush.setText(_translate("MainWindow", "Clear"))
        self.RandomPush.setText(_translate("MainWindow", "Shuffle"))
        self.label_2.setText(_translate("MainWindow", "Config"))
        self.NumBox.setText(_translate("MainWindow", "Numbers"))
        self.LetterBox.setText(_translate("MainWindow", "Letters"))
        self.SpecialBox.setText(_translate("MainWindow", "Special Symbols"))
        self.RandBox.setText(_translate("MainWindow", "Random length"))
        self.CapsBox.setText(_translate("MainWindow", "CAPS"))
        self.BaseBox.setText(_translate("MainWindow", "Base64"))
        self.label_5.setText(_translate("MainWindow", "Length"))
        self.CopyPush.setText(_translate("MainWindow", "Copy"))
        self.menuFileSaver.setTitle(_translate("MainWindow", "File"))
        self.menuHashes.setTitle(_translate("MainWindow", "Hashes"))
        self.menuAbout.setTitle(_translate("MainWindow", "Settings"))
        self.menuChange_language.setTitle(_translate("MainWindow", "Change language"))
        self.actionFile.setText(_translate("MainWindow", "Save to file"))
        self.actionsha512.setText(_translate("MainWindow", "sha512"))
        self.actionsha256.setText(_translate("MainWindow", "sha256"))
        self.actionsha_1.setText(_translate("MainWindow", "sha-1"))
        self.actionblake2b.setText(_translate("MainWindow", "blake2b"))
        self.actionGenerate_5_times.setText(_translate("MainWindow", "Generate 5 times"))
        self.actionGenerate_10_times.setText(_translate("MainWindow", "Generate 10 times"))
        self.actionGenerate_50_times.setText(_translate("MainWindow", "Generate 50 times"))
        self.actionGenerate_100_times.setText(_translate("MainWindow", "Generate 100 times"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action10.setText(_translate("MainWindow", "10"))
        self.action20.setText(_translate("MainWindow", "20"))
        self.action50.setText(_translate("MainWindow", "50"))
        self.action100.setText(_translate("MainWindow", "100"))
        self.actionNot_save.setText(_translate("MainWindow", "Not save"))
        self.actionGenerate_Multiply_Times.setText(_translate("MainWindow", "Generate Multiply Times"))
        self.actionRussian.setText(_translate("MainWindow", "Russian"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
