# Form implementation generated from reading ui file 'module_multiply_generator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 111, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(parent=Dialog)
        self.progressBar.setGeometry(QtCore.QRect(120, 160, 181, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Slider = QtWidgets.QSlider(parent=Dialog)
        self.Slider.setGeometry(QtCore.QRect(80, 200, 211, 22))
        self.Slider.setMaximum(1000)
        self.Slider.setTracking(True)
        self.Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider.setObjectName("Slider")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 180, 111, 31))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 230, 239, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GenerateMultiply = QtWidgets.QPushButton(parent=self.widget)
        self.GenerateMultiply.setObjectName("GenerateMultiply")
        self.horizontalLayout.addWidget(self.GenerateMultiply)
        self.SelectFile = QtWidgets.QPushButton(parent=self.widget)
        self.SelectFile.setObjectName("SelectFile")
        self.horizontalLayout.addWidget(self.SelectFile)
        self.CancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Multiply Generator"))
        self.label_2.setText(_translate("Dialog", "Value:"))
        self.GenerateMultiply.setText(_translate("Dialog", "Generate"))
        self.SelectFile.setText(_translate("Dialog", "Select a file"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
